name: Build and Deploy to Plesk via FTP

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_COMMAND: npm ci && npm run build
      DIST_DIR: dist

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js (remove or change if not a Node project)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & Build
        run: |
          echo "→ Running build command"
          $BUILD_COMMAND

      - name: Show dist contents (sanity)
        run: |
          echo "→ Dist dir listing:"
          ls -la ${{ env.DIST_DIR }}

      - name: Deploy via FTP to Plesk
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./${{ env.DIST_DIR }}
          server-dir: ${{ secrets.FTP_TARGET_PATH }}
